Attaching to nginx, mongo, dashbard, watchdog, restserver
[36mnginx         |[0m Adding password for user admin
[36mnginx         |[0m 2017/06/07 22:26:07 [error] 10#10: *2 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.102, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/07 22:26:07 [error] 10#10: *2 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.102, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/07 22:26:15 [error] 10#10: *2 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.102, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/07 22:26:15 [error] 10#10: *2 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.102, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/07 22:26:40 [error] 10#10: *5 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.102, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/07 22:26:40 [error] 10#10: *5 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.102, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/07 22:26:43 [error] 10#10: *5 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.102, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8080/favicon.ico", host: "10.101.35.60:8080", referrer: "http://10.101.35.60:8080/"
[36mnginx         |[0m 2017/06/07 22:26:43 [error] 10#10: *5 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.102, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8080/favicon.ico", host: "10.101.35.60:8080", referrer: "http://10.101.35.60:8080/"
[36mnginx         |[0m 2017/06/08 15:33:26 [error] 10#10: *9 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.97, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/08 15:33:26 [error] 10#10: *9 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.97, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:8080/", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/08 15:33:30 [error] 10#10: *9 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.97, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8080/favicon.ico", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/08 15:33:30 [error] 10#10: *9 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.97, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8080/favicon.ico", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/08 15:33:33 [error] 10#10: *9 connect() failed (113: No route to host) while connecting to upstream, client: 10.0.60.97, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8080/favicon.ico", host: "10.101.35.60:8080"
[36mnginx         |[0m 2017/06/08 15:33:33 [error] 10#10: *9 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 10.0.60.97, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.3:8080/favicon.ico", host: "10.101.35.60:8080"
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=mongo
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] db version v3.2.13
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] git version: 23899209cad60aaafe114f6aea6cb83025ff51bc
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] modules: none
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] build environment:
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten]     distmod: debian81
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten]     distarch: x86_64
[32mdashbard      |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[33mmongo         |[0m 2017-06-07T14:23:09.012+0000 I CONTROL  [initandlisten] options: {}
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:09.015+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=8G,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] 
[32mdashbard      |[0m     from .index import bp_index
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] 
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
[32mdashbard      |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T14:23:09.053+0000 I CONTROL  [initandlisten] 
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T14:23:09.065+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
[31mrestserver    |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:23:09.066+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[35mwatchdog      |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:23:09.066+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from resources import front_rest_v2
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-07T14:23:09.880+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58930 #1 (1 connection now open)
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-07T14:23:10.158+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42252 #2 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:10.647+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38130 #3 (3 connections now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m     from docker import Client
[33mmongo         |[0m 2017-06-07T14:23:10.892+0000 I NETWORK  [conn1] end connection 172.18.0.3:58930 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:11.172+0000 I NETWORK  [conn2] end connection 172.18.0.2:42252 (1 connection now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[33mmongo         |[0m 2017-06-07T14:23:11.423+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58936 #4 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:11.658+0000 I NETWORK  [conn3] end connection 172.18.0.4:38130 (1 connection now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:23:11.987+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42258 #5 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:12.371+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38136 #6 (3 connections now open)
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[33mmongo         |[0m 2017-06-07T14:23:12.436+0000 I NETWORK  [conn4] end connection 172.18.0.3:58936 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:12.999+0000 I NETWORK  [conn5] end connection 172.18.0.2:42258 (1 connection now open)
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from resources import front_rest_v2
[33mmongo         |[0m 2017-06-07T14:23:13.030+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58942 #7 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:13.383+0000 I NETWORK  [conn6] end connection 172.18.0.4:38136 (1 connection now open)
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:13.890+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42264 #8 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:14.041+0000 I NETWORK  [conn7] end connection 172.18.0.3:58942 (1 connection now open)
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m     from .index import bp_index
[33mmongo         |[0m 2017-06-07T14:23:14.290+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38142 #9 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:14.874+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58948 #10 (3 connections now open)
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[33mmongo         |[0m 2017-06-07T14:23:14.903+0000 I NETWORK  [conn8] end connection 172.18.0.2:42264 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:15.301+0000 I NETWORK  [conn9] end connection 172.18.0.4:38142 (1 connection now open)
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[33mmongo         |[0m 2017-06-07T14:23:15.884+0000 I NETWORK  [conn10] end connection 172.18.0.3:58948 (0 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:16.274+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42270 #11 (1 connection now open)
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m     from resources import bp_index, \
[33mmongo         |[0m 2017-06-07T14:23:16.628+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58952 #12 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:23:17.057+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38150 #13 (3 connections now open)
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T14:23:17.288+0000 I NETWORK  [conn11] end connection 172.18.0.2:42270 (2 connections now open)
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T14:23:17.640+0000 I NETWORK  [conn12] end connection 172.18.0.3:58952 (1 connection now open)
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T14:23:18.067+0000 I NETWORK  [conn13] end connection 172.18.0.4:38150 (0 connections now open)
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:18.823+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42276 #14 (1 connection now open)
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[33mmongo         |[0m 2017-06-07T14:23:19.723+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58958 #15 (2 connections now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-07T14:23:19.835+0000 I NETWORK  [conn14] end connection 172.18.0.2:42276 (1 connection now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from docker import Client
[33mmongo         |[0m 2017-06-07T14:23:20.049+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38156 #16 (2 connections now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[33mmongo         |[0m 2017-06-07T14:23:20.734+0000 I NETWORK  [conn15] end connection 172.18.0.3:58958 (1 connection now open)
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:21.060+0000 I NETWORK  [conn16] end connection 172.18.0.4:38156 (0 connections now open)
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:22.087+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42282 #17 (1 connection now open)
[33mmongo         |[0m 2017-06-07T14:23:23.100+0000 I NETWORK  [conn17] end connection 172.18.0.2:42282 (0 connections now open)
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[33mmongo         |[0m 2017-06-07T14:23:24.533+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42284 #18 (1 connection now open)
[33mmongo         |[0m 2017-06-07T14:23:24.980+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58966 #19 (2 connections now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-07T14:23:25.544+0000 I NETWORK  [conn18] end connection 172.18.0.2:42284 (1 connection now open)
[33mmongo         |[0m 2017-06-07T14:23:25.991+0000 I NETWORK  [conn19] end connection 172.18.0.3:58966 (0 connections now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from docker import Client
[33mmongo         |[0m 2017-06-07T14:23:26.961+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42288 #20 (1 connection now open)
[33mmongo         |[0m 2017-06-07T14:23:27.971+0000 I NETWORK  [conn20] end connection 172.18.0.2:42288 (0 connections now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[33mmongo         |[0m 2017-06-07T14:23:32.393+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42290 #21 (1 connection now open)
[33mmongo         |[0m 2017-06-07T14:23:32.767+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58972 #22 (2 connections now open)
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:33.405+0000 I NETWORK  [conn21] end connection 172.18.0.2:42290 (1 connection now open)
[33mmongo         |[0m 2017-06-07T14:23:33.777+0000 I NETWORK  [conn22] end connection 172.18.0.3:58972 (0 connections now open)
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m     from resources import front_rest_v2
[33mmongo         |[0m 2017-06-07T14:23:35.002+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42294 #23 (1 connection now open)
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:36.013+0000 I NETWORK  [conn23] end connection 172.18.0.2:42294 (0 connections now open)
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m     from .index import bp_index
[33mmongo         |[0m 2017-06-07T14:23:46.691+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42296 #24 (1 connection now open)
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[33mmongo         |[0m 2017-06-07T14:23:47.000+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58978 #25 (2 connections now open)
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[33mmongo         |[0m 2017-06-07T14:23:47.702+0000 I NETWORK  [conn24] end connection 172.18.0.2:42296 (1 connection now open)
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:48.010+0000 I NETWORK  [conn25] end connection 172.18.0.3:58978 (0 connections now open)
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from docker import Client
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T14:23:49.620+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42300 #26 (1 connection now open)
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:23:50.634+0000 I NETWORK  [conn26] end connection 172.18.0.2:42300 (0 connections now open)
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[33mmongo         |[0m 2017-06-07T14:24:13.745+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42302 #27 (1 connection now open)
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-07T14:24:13.987+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58984 #28 (2 connections now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from docker import Client
[33mmongo         |[0m 2017-06-07T14:24:14.755+0000 I NETWORK  [conn27] end connection 172.18.0.2:42302 (1 connection now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[33mmongo         |[0m 2017-06-07T14:24:14.998+0000 I NETWORK  [conn28] end connection 172.18.0.3:58984 (0 connections now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:24:16.896+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42306 #29 (1 connection now open)
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[33mmongo         |[0m 2017-06-07T14:24:17.906+0000 I NETWORK  [conn29] end connection 172.18.0.2:42306 (0 connections now open)
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m     from resources import front_rest_v2
[33mmongo         |[0m 2017-06-07T14:25:32.912+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:58988 #30 (1 connection now open)
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:25:33.927+0000 I NETWORK  [conn30] end connection 172.18.0.3:58988 (0 connections now open)
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m     from .index import bp_index
[33mmongo         |[0m 2017-06-07T14:25:34.063+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42310 #31 (1 connection now open)
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[33mmongo         |[0m 2017-06-07T14:25:34.212+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38188 #32 (2 connections now open)
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[33mmongo         |[0m 2017-06-07T14:25:35.073+0000 I NETWORK  [conn31] end connection 172.18.0.2:42310 (1 connection now open)
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:25:35.223+0000 I NETWORK  [conn32] end connection 172.18.0.4:38188 (0 connections now open)
[33mmongo         |[0m 2017-06-07T14:27:16.731+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42322 #33 (1 connection now open)
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T14:27:17.743+0000 I NETWORK  [conn33] end connection 172.18.0.2:42322 (0 connections now open)
[33mmongo         |[0m 2017-06-07T14:27:17.922+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59004 #34 (1 connection now open)
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T14:27:18.302+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.4:38202 #35 (2 connections now open)
[33mmongo         |[0m 2017-06-07T14:27:18.933+0000 I NETWORK  [conn34] end connection 172.18.0.3:59004 (1 connection now open)
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T14:27:19.313+0000 I NETWORK  [conn35] end connection 172.18.0.4:38202 (0 connections now open)
[33mmongo         |[0m 2017-06-07T14:30:42.921+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42328 #36 (1 connection now open)
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:30:43.932+0000 I NETWORK  [conn36] end connection 172.18.0.2:42328 (0 connections now open)
[33mmongo         |[0m 2017-06-07T14:30:44.240+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59010 #37 (1 connection now open)
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T14:30:44.782+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42332 #38 (2 connections now open)
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T14:30:45.251+0000 I NETWORK  [conn37] end connection 172.18.0.3:59010 (1 connection now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m     from docker import Client
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T14:30:45.793+0000 I NETWORK  [conn38] end connection 172.18.0.2:42332 (0 connections now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T14:37:33.964+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42334 #39 (1 connection now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:37:34.975+0000 I NETWORK  [conn39] end connection 172.18.0.2:42334 (0 connections now open)
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[33mmongo         |[0m 2017-06-07T14:37:35.342+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59016 #40 (1 connection now open)
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[33mmongo         |[0m 2017-06-07T14:37:36.085+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42338 #41 (2 connections now open)
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from docker import Client
[33mmongo         |[0m 2017-06-07T14:37:36.353+0000 I NETWORK  [conn40] end connection 172.18.0.3:59016 (1 connection now open)
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[33mmongo         |[0m 2017-06-07T14:37:37.096+0000 I NETWORK  [conn41] end connection 172.18.0.2:42338 (0 connections now open)
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T14:51:14.578+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42340 #42 (1 connection now open)
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[33mmongo         |[0m 2017-06-07T14:51:15.589+0000 I NETWORK  [conn42] end connection 172.18.0.2:42340 (0 connections now open)
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[33mmongo         |[0m 2017-06-07T14:51:16.047+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59022 #43 (1 connection now open)
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T14:51:16.977+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42344 #44 (2 connections now open)
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T14:51:17.058+0000 I NETWORK  [conn43] end connection 172.18.0.3:59022 (1 connection now open)
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T14:51:17.988+0000 I NETWORK  [conn44] end connection 172.18.0.2:42344 (0 connections now open)
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T15:18:34.354+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42346 #45 (1 connection now open)
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[33mmongo         |[0m 2017-06-07T15:18:35.364+0000 I NETWORK  [conn45] end connection 172.18.0.2:42346 (0 connections now open)
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-07T15:18:35.995+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42348 #46 (1 connection now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from docker import Client
[33mmongo         |[0m 2017-06-07T15:18:37.007+0000 I NETWORK  [conn46] end connection 172.18.0.2:42348 (0 connections now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[33mmongo         |[0m 2017-06-07T15:18:37.035+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59030 #47 (1 connection now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m Traceback (most recent call last):
[33mmongo         |[0m 2017-06-07T15:18:38.046+0000 I NETWORK  [conn47] end connection 172.18.0.3:59030 (0 connections now open)
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[33mmongo         |[0m 2017-06-07T16:13:12.659+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42352 #48 (1 connection now open)
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[33mmongo         |[0m 2017-06-07T16:13:13.670+0000 I NETWORK  [conn48] end connection 172.18.0.2:42352 (0 connections now open)
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T16:13:14.264+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42354 #49 (1 connection now open)
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .index import bp_index
[33mmongo         |[0m 2017-06-07T16:13:15.274+0000 I NETWORK  [conn49] end connection 172.18.0.2:42354 (0 connections now open)
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[33mmongo         |[0m 2017-06-07T16:13:15.488+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59036 #50 (1 connection now open)
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[33mmongo         |[0m 2017-06-07T16:13:16.501+0000 I NETWORK  [conn50] end connection 172.18.0.3:59036 (0 connections now open)
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T18:02:27.675+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42358 #51 (1 connection now open)
[32mdashbard      |[0m     from resources import bp_index, \
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T18:02:28.686+0000 I NETWORK  [conn51] end connection 172.18.0.2:42358 (0 connections now open)
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T18:02:29.410+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42360 #52 (1 connection now open)
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T18:02:30.421+0000 I NETWORK  [conn52] end connection 172.18.0.2:42360 (0 connections now open)
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T18:02:30.788+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59042 #53 (1 connection now open)
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[33mmongo         |[0m 2017-06-07T18:02:31.801+0000 I NETWORK  [conn53] end connection 172.18.0.3:59042 (0 connections now open)
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[33mmongo         |[0m 2017-06-07T21:40:56.288+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42366 #54 (1 connection now open)
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m     from docker import Client
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[33mmongo         |[0m 2017-06-07T21:40:57.298+0000 I NETWORK  [conn54] end connection 172.18.0.2:42366 (0 connections now open)
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-07T21:40:58.079+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42368 #55 (1 connection now open)
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-07T21:40:59.090+0000 I NETWORK  [conn55] end connection 172.18.0.2:42368 (0 connections now open)
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[33mmongo         |[0m 2017-06-07T21:40:59.671+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.3:59050 #56 (1 connection now open)
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from resources import front_rest_v2
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[33mmongo         |[0m 2017-06-07T21:41:00.683+0000 I NETWORK  [conn56] end connection 172.18.0.3:59050 (0 connections now open)
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-08T04:57:52.109+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42376 #57 (1 connection now open)
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m     from .index import bp_index
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[33mmongo         |[0m 2017-06-08T04:57:53.119+0000 I NETWORK  [conn57] end connection 172.18.0.2:42376 (0 connections now open)
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[33mmongo         |[0m 2017-06-08T04:57:53.941+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42378 #58 (1 connection now open)
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[33mmongo         |[0m 2017-06-08T04:57:54.952+0000 I NETWORK  [conn58] end connection 172.18.0.2:42378 (0 connections now open)
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[33mmongo         |[0m 2017-06-08T04:57:55.716+0000 I NETWORK  [initandlisten] connection accepted from 172.18.0.2:42380 #59 (1 connection now open)
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from .cluster import cluster_handler
[33mmongo         |[0m 2017-06-08T04:57:56.728+0000 I NETWORK  [conn59] end connection 172.18.0.2:42380 (0 connections now open)
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from docker import Client
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from resources import front_rest_v2
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m     from .index import bp_index
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m Traceback (most recent call last):
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m     from resources import front_rest_v2
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m     from resources import bp_index, \
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m     from .index import bp_index
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from docker import Client
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from docker import Client
[35mwatchdog      |[0m     from docker import Client
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m Traceback (most recent call last):
[35mwatchdog      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m     from .index import bp_index
[35mwatchdog      |[0m   File "watchdog.py", line 6, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[35mwatchdog      |[0m     from modules import host_handler, cluster_handler
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[35mwatchdog      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[35mwatchdog      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[35mwatchdog      |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[35mwatchdog      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[35mwatchdog      |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[35mwatchdog      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[35mwatchdog      |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from docker import Client
[35mwatchdog      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m     from .index import bp_index
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from .cluster import cluster_handler
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m Traceback (most recent call last):
[31mrestserver    |[0m     from resources import front_rest_v2
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m     from .index import bp_index
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from docker import Client
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m Traceback (most recent call last):
[32mdashbard      |[0m     from docker import Client
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[32mdashbard      |[0m Traceback (most recent call last):
[32mdashbard      |[0m   File "dashboard.py", line 4, in <module>
[32mdashbard      |[0m     from resources import bp_index, \
[32mdashbard      |[0m   File "/app/resources/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from .index import bp_index
[32mdashbard      |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[32mdashbard      |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .index import bp_index
[32mdashbard      |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[32mdashbard      |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[32mdashbard      |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[32mdashbard      |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[32mdashbard      |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[32mdashbard      |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[32mdashbard      |[0m     from docker import Client
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[32mdashbard      |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from docker import Client
[31mrestserver    |[0m ImportError: cannot import name 'Client'
[31mrestserver    |[0m Traceback (most recent call last):
[31mrestserver    |[0m   File "restserver.py", line 5, in <module>
[31mrestserver    |[0m     from resources import front_rest_v2
[31mrestserver    |[0m   File "/app/resources/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .index import bp_index
[31mrestserver    |[0m   File "/app/resources/index.py", line 17, in <module>
[31mrestserver    |[0m     from modules import cluster_handler, host_handler
[31mrestserver    |[0m   File "/app/modules/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .cluster import cluster_handler
[31mrestserver    |[0m   File "/app/modules/cluster.py", line 14, in <module>
[31mrestserver    |[0m     from agent import get_swarm_node_ip, \
[31mrestserver    |[0m   File "/app/agent/__init__.py", line 1, in <module>
[31mrestserver    |[0m     from .docker_swarm import get_project, \
[31mrestserver    |[0m   File "/app/agent/docker_swarm.py", line 10, in <module>
[31mrestserver    |[0m     from docker import Client
[31mrestserver    |[0m ImportError: cannot import name 'Client'
